# Generated by Django 6.0.7 on 2026-07-29 13:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportRun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('executed_at', models.DateTimeField(auto_now_add=True)),
                ('total_devices', models.PositiveIntegerField(default=0)),
                ('success', models.BooleanField(default=True)),
                ('error_message', models.TextField(blank=True, default='')),
            ],
            options={
                'ordering': ['-executed_at'],
            },
        ),
        migrations.CreateModel(
            name='DeviceSnapshot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(blank=True, default='', max_length=255)),
                ('ip_address', models.CharField(blank=True, default='', max_length=45)),
                ('page_count', models.BigIntegerField(blank=True, null=True)),
                ('captured_at', models.DateTimeField(db_index=True)),
                ('run', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='snapshots', to='devices.exportrun')),
            ],
            options={
                'ordering': ['model_name', 'ip_address'],
                'indexes': [models.Index(fields=['ip_address', 'captured_at'], name='devices_dev_ip_addr_5f0be1_idx'), models.Index(fields=['run', 'ip_address'], name='devices_dev_run_id_45b583_idx')],
            },
        ),
    ]
