# Generated by Django 6.0.7 on 2026-07-29 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnapshot',
            name='device_status_severity',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
        migrations.AddField(
            model_name='devicesnapshot',
            name='display_name',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
