# Generated by Django 6.0.7 on 2026-07-29 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0002_devicesnapshot_device_status_severity_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='devicesnapshot',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AddField(
            model_name='devicesnapshot',
            name='system_location',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
