# Generated by Django 6.0.7 on 2026-07-29 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0003_devicesnapshot_serial_number_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportSchedule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enabled', models.BooleanField(default=True, help_text='Si esta desactivado, el export no se ejecutara automaticamente.')),
                ('run_time', models.TimeField(help_text='Hora del dia (servidor) en la que se ejecuta el export automaticamente.')),
                ('last_run_date', models.DateField(blank=True, editable=False, help_text='Ultima fecha en que corrio automaticamente.', null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Configuracion de horario',
                'verbose_name_plural': 'Configuracion de horario',
            },
        ),
    ]
