# Generated by Django 6.0.7 on 2026-07-29 15:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0004_exportschedule'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportschedule',
            name='last_run_date',
        ),
    ]
