# Generated by Django 6.0.7 on 2026-07-30 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0005_remove_exportschedule_last_run_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='MonthlyCounterEntry',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(blank=True, default='', max_length=100)),
                ('office_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre Oficina')),
                ('floor', models.CharField(blank=True, default='', max_length=100, verbose_name='Piso')),
                ('host_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre de Host Sede')),
                ('location', models.CharField(blank=True, default='', max_length=255, verbose_name='Asignada o Ubicacion')),
                ('display_name', models.CharField(blank=True, default='', max_length=255, verbose_name='DisplayName')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45, verbose_name='IPv4Address')),
                ('serial_number', models.CharField(blank=True, default='', max_length=100, verbose_name='SerialNumber')),
                ('previous_month_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador del Mes Anterior')),
                ('week1_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Semana 1')),
                ('week1_final', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Final Semana 1')),
                ('week2_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Semana 2')),
                ('week2_final', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Final Semana 2')),
                ('week3_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Semana 3')),
                ('week3_final', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Final Semana 3')),
                ('week4_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Semana 4')),
                ('week4_final', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Final Semana 4')),
                ('week5_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Semana 5')),
                ('week5_final', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Final Semana 5')),
                ('monthly_counter', models.BigIntegerField(blank=True, null=True, verbose_name='Contador Mensual')),
                ('zero_counter_devices', models.IntegerField(blank=True, null=True, verbose_name='Equipos con contadores en 0')),
                ('period', models.CharField(blank=True, default='', help_text='Ej: jun-26', max_length=20, verbose_name='Fecha')),
                ('observations', models.TextField(blank=True, default='', verbose_name='Observaciones')),
                ('printer_status', models.CharField(blank=True, default='', max_length=100, verbose_name='Status Impresora')),
                ('source_file', models.CharField(blank=True, default='', max_length=255)),
                ('imported_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'Contador mensual',
                'verbose_name_plural': 'Contadores mensuales',
                'ordering': ['-imported_at'],
                'indexes': [models.Index(fields=['ip_address', 'period'], name='devices_mon_ip_addr_1e23dd_idx'), models.Index(fields=['region', 'period'], name='devices_mon_region_61e5de_idx')],
            },
        ),
    ]
