# Generated by Django 6.0.7 on 2026-07-31 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0007_oficina_remove_monthlycounterentry_office_name_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='oficina',
            name='code',
            field=models.CharField(blank=True, default='', max_length=50, verbose_name='Codigo de Oficina'),
        ),
        migrations.AddField(
            model_name='oficina',
            name='region',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Region'),
        ),
    ]
