# Generated by Django 6.0.7 on 2026-07-31 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0008_oficina_code_oficina_region'),
    ]

    operations = [
        migrations.CreateModel(
            name='Impresora',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, default='', max_length=255, verbose_name='Nombre')),
                ('model_name', models.CharField(blank=True, default='', max_length=255, verbose_name='Modelo')),
                ('ip_address', models.CharField(blank=True, default='', max_length=45, verbose_name='IP')),
                ('status', models.CharField(blank=True, default='', max_length=100, verbose_name='Status')),
            ],
            options={
                'verbose_name': 'Impresora',
                'verbose_name_plural': 'Impresoras',
                'ordering': ['name'],
            },
        ),
    ]
