# Generated by Django 6.0.7 on 2026-07-31 18:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0009_impresora'),
    ]

    operations = [
        migrations.AddField(
            model_name='impresora',
            name='serial_number',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Serial'),
        ),
        migrations.AddField(
            model_name='monthlycounterentry',
            name='impresora',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='monthly_entries', to='devices.impresora', verbose_name='Impresora'),
        ),
    ]
