# Generated by Django 6.0.7 on 2026-07-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0010_impresora_serial_number_and_more'),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name='monthlycounterentry',
            name='devices_mon_ip_addr_1e23dd_idx',
        ),
        migrations.AddIndex(
            model_name='monthlycounterentry',
            index=models.Index(fields=['impresora', 'period'], name='devices_mon_impreso_16131d_idx'),
        ),
        migrations.RemoveField(
            model_name='monthlycounterentry',
            name='display_name',
        ),
        migrations.RemoveField(
            model_name='monthlycounterentry',
            name='host_name',
        ),
        migrations.RemoveField(
            model_name='monthlycounterentry',
            name='ip_address',
        ),
        migrations.RemoveField(
            model_name='monthlycounterentry',
            name='printer_status',
        ),
        migrations.RemoveField(
            model_name='monthlycounterentry',
            name='serial_number',
        ),
    ]
