# Generated by Django 6.0.7 on 2026-08-10 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0012_impresora_serial_number_unique'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycounterentry',
            name='ip_address',
            field=models.CharField(blank=True, default='', max_length=45, verbose_name='IP del periodo'),
        ),
        migrations.AddIndex(
            model_name='monthlycounterentry',
            index=models.Index(fields=['ip_address', 'period'], name='devices_mon_ip_addr_1e23dd_idx'),
        ),
    ]
