# Generated by Django 6.0.7 on 2026-08-10 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0013_monthlycounterentry_ip_address_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycounterentry',
            name='printer_status',
            field=models.CharField(blank=True, default='', max_length=100, verbose_name='Status Impresora del periodo'),
        ),
    ]
