# Generated by Django 6.0.7 on 2026-08-10 16:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0014_monthlycounterentry_printer_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycounterentry',
            name='category',
            field=models.CharField(blank=True, default='', help_text='Oficina o Torre, segun el reporte de origen.', max_length=20, verbose_name='Categoria'),
        ),
    ]
