# Generated by Django 6.0.7 on 2026-08-19 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0016_normalize_cierre_definitivo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='impresora',
            name='status',
            field=models.CharField(blank=True, choices=[('Instalado', 'Instalado'), ('Cierre temporal', 'Cierre temporal'), ('Pendiente Retiro', 'Pendiente Retiro'), ('Cierre definitivo', 'Cierre definitivo'), ('Embalada', 'Embalada'), ('Perdida Total', 'Perdida Total'), ('Resguardo en la Agencia', 'Resguardo en la Agencia'), ('Desistalada', 'Desistalada')], default='', max_length=100, verbose_name='Status'),
        ),
        migrations.AlterField(
            model_name='monthlycounterentry',
            name='printer_status',
            field=models.CharField(blank=True, choices=[('Instalado', 'Instalado'), ('Cierre temporal', 'Cierre temporal'), ('Pendiente Retiro', 'Pendiente Retiro'), ('Cierre definitivo', 'Cierre definitivo'), ('Embalada', 'Embalada'), ('Perdida Total', 'Perdida Total'), ('Resguardo en la Agencia', 'Resguardo en la Agencia'), ('Desistalada', 'Desistalada')], default='', max_length=100, verbose_name='Status Impresora del periodo'),
        ),
    ]
