# Generated by Django 6.0.7 on 2026-08-21 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('devices', '0019_normalize_metro_region'),
    ]

    operations = [
        migrations.AddField(
            model_name='monthlycounterentry',
            name='agency_status',
            field=models.CharField(blank=True, default='', help_text="Valor de la columna 'Estatus Agencia' del Excel de Oficina para ese periodo, tal cual viene reportado (no confundir con Oficina.status, que es el estatus actual del catalogo de oficinas).", max_length=100, verbose_name='Estatus Agencia del periodo'),
        ),
    ]
